#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# assume image will be run with libvirt using the default network
echo 'nameserver 192.168.122.1' > /etc/resolv.conf.ORIG
